/**:
  ros__parameters:
    matrix_file:
      # Camera projection matrix P from camera_info (1280x720).
      camera_matrix:
      - 633.8698120117188
      - 0.0
      - 635.5365600585938
      - 0.0
      - 0.0
      - 633.1943359375
      - 358.7809143066406
      - 0.0
      - 0.0
      - 0.0
      - 1.0
      - 0.0

      # Direct LiDAR -> camera_color_optical_frame extrinsic rotation.
      rlc:
      - -0.12360466
      - -0.99233162
      - 0.0
      - 0.0
      - 0.0
      - -1.0
      - 0.99233162
      - -0.12360460
      - 0.0

      # Direct LiDAR -> camera_color_optical_frame extrinsic translation [m].
      tlc:
      - -0.01
      - 0.10
      - -0.09
