/**:
  ros__parameters:
    pcTopic: /pc_interpoled
    imgTopic: /camera/color/image_raw
    sync_queue_size: 10
    overlay_max_range_m: 50.0

    output_cloud_topic: /points2
    output_image_topic: /pcOnImage_image
